<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhuk0b5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhuk0b5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMhuk0b5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMhuk0b5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMhuk0b5\appProdProjectContainer([
    'container.build_hash' => 'Mhuk0b5',
    'container.build_id' => '430f895a',
    'container.build_time' => 1720619368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhuk0b5');
